### ISSUE TITLE
Timezone?

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/muenster-jetzt#113]
So what's the timezone of events returned by the backend?

My opinion is: We should store event start/end times in UTC and return them as such. The front end is then responsible for displaying the correct time depending on: the time zone of the computer displaying the front end and the date/time of the event.

This should also be documented and also reflected in api responses. (Adding `Z` to time responses)

WDYT? @bCyberBasti @jdemaeyer

**Comment by bCyberBasti** [comment]
UTC sounds like a Great idea 👍

**Comment by ubergesundheit** [comment]
@jdemaeyer Do you have an opinion on this or could quickly chime in how its implemented right now?

**Comment by jdemaeyer** [comment]
Currently we store dates and times without timezone since that info is not supplied by our source, i.e. if we wanted to add it we would simply move the guesswork from the user brain to some fuzzy logic we'd have to come up with.

For now all times are local to the event location, which is also how I would expect the time to be displayed to me as a frontend user, regardless of what timezone my computer sits in, and [how the big event sites display it](https://www.ticketmaster.com/event/1B005845E2B1853F). In other words, for displaying times like this the frontend would ignore the time zone anyways, at most displaying it as an extra field or hover text. (Online events are a special case but detecting what is online and what is local from the location string is opening a whole other can of worms...)

In any case, I don't think this is a very pressing issue as long as this is a Münster-only (or even Germany-only) service but I don't have any strong opinions, so if you guys feel it's easier or more future-proof to slap a hard-coded timezone onto the `startTime` and `endTime` fields I'm down with that :)

**Comment by ubergesundheit** [comment]
I was asking because I had the following things in mind:

- For end users we want to display something like: `in x days/hours`. For this to work, the browser needs to parse the given date/time and I would like to avoid undefined behaviour here
- For other api users I can imagine one of the use cases woule be to compare the start/end to some other dates of other data sources. I imagine this mainly happening on servers using the UTC time zone.

I admit, since we mainly deal with events and users in the same time zone, this is not really imporant and can (should) be hardcoded in the backend, but leaving this entirely open leaves a bad taste in my mouth for some reason.

I would be happy if the backend could make some educated guess about the time zone. Basically checking if the event is in CET or CEST and then subtracting 1 or 2 hours and then store and return the event times as UTC.

**Comment by jdemaeyer** [comment]
Alrighty -> #121 

> Basically checking if the event is in CET or CEST and then subtracting 1 or 2 hours and then store and return the event times as UTC.

If we store in UTC we lose the "local time" information (as we won't know what time zone the event is located in), so I'll store as `20:00+02:00`. I'd also prefer to return it like this since otherwise you have the same problem in the frontend (and won't be able to display the event-local times unless you guess the event location time zone)

**Comment by ubergesundheit** [comment]
Ok, agreed. Any returned time zone is better than none :+1:

**Comment by ubergesundheit** [comment]
We'll close this in favour of #121
